name: Build Jekyll Site into /docs

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '_config.yml'
      - 'Gemfile*'
      - '.github/workflows/build-docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --source src --destination docs

      - name: Commit /docs back to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "📦 Rebuild static site into /docs"
          git push
